#!/usr/bin/env php

<?php
require 'vendor/docopt/docopt/src/docopt.php';

$doc = <<<DOC
Generate diff

Usage:
  gendiff (-h|--help)
  gendiff (-v|--version)

Options:
  -h --help     Show this screen
  -v --version  Show version

DOC;

$args = Docopt::handle($doc);